api-gateway:
  build:
    context: ./ApiGateway
  container_name: api-gateway
    depends_on:
      - billingserviceapi
      - bookserviceapi
      - orderserviceapi
      - userserviceapi
    environment:
      ASPNETCORE_URLS: "production"
    pull_policy: always